##################################################################################################
# Foo service
##################################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-service
  labels:
    app: foo
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foo
      version: v1
  template:
    metadata:
      labels:
        app: foo
        version: v1
    spec:
      containers:
        - name: foo
          image: docker.io/softshipper/foo-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: foo
  labels:
    app: foo
    service: foo
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: foo